FROM node:22.18.0

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY . .

RUN CI=true pnpm install --frozen-lockfile

COPY . /app

CMD ["pnpm", "run", "start", "--host", "0.0.0.0"]
